# Generated by Django 5.1.6 on 2025-03-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CulturalPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coord", models.CharField(max_length=200)),
                ("location_name", models.CharField(max_length=200)),
                ("info", models.CharField(max_length=200)),
            ],
        ),
    ]
